
// Objective-C API for talking to the following Go packages
//
//	gitlab.zalopay.vn/apps/corelib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Corelib_FRAMEWORK_H__
#define __Corelib_FRAMEWORK_H__

#include "Corelib.objc.h"
#include "universe.objc.h"

#endif
