// Objective-C API for talking to gitlab.zalopay.vn/apps/corelib Go package.
//   gobind -lang=objc gitlab.zalopay.vn/apps/corelib
//
// File is generated by gobind. Do not edit.

#ifndef __Corelib_H__
#define __Corelib_H__

@import Foundation;
#include "Universe.objc.h"


@class CorelibZPCoreDB;
@class CorelibZpConfigResponse;
@class CorelibZpData;
@protocol CorelibOmniP;
@class CorelibOmniP;
@protocol CorelibZpConfig;
@class CorelibZpConfig;

@protocol CorelibOmniP <NSObject>
- (BOOL)login:(NSString*)userID accessToken:(NSString*)accessToken;
- (void)logout;
- (BOOL)submit:(NSData*)data;
@end

@protocol CorelibZpConfig <NSObject>
- (NSData*)getValueForKey:(NSString*)jsonkeys error:(NSError**)error;
@end

@interface CorelibZPCoreDB : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init:(NSString*)dbPath;
- (void)close;
- (NSString*)getValueForKey:(NSString*)key error:(NSError**)error;
- (void)removeKey:(NSString*)key;
- (void)setValueForKey:(NSString*)key value:(NSString*)value;
@end

@interface CorelibZpConfigResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)key;
- (void)setKey:(NSString*)v;
- (NSString*)value;
- (void)setValue:(NSString*)v;
@end

@interface CorelibZpData : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field ZpData.Data with unsupported type: []*gitlab.zalopay.vn/apps/corelib.ZpConfigResponse

@end

/**
 * GetVersion returns current version of ZPAC library
 */
FOUNDATION_EXPORT NSString* CorelibGetVersion(void);

/**
 * NewOmniP create new instance of OmniP and initialize some internal data
 */
FOUNDATION_EXPORT id<CorelibOmniP> CorelibNewOmniP(NSString* baseURL, NSString* dataPath, NSString* publicKey, NSError** error);

FOUNDATION_EXPORT CorelibZPCoreDB* CorelibNewZPCoreDB(NSString* dbPath);

FOUNDATION_EXPORT id<CorelibZpConfig> CorelibNewZpConfig(NSString* baseURL, NSString* accessToken, NSString* databasePath, NSError** error);

@class CorelibOmniP;

@class CorelibZpConfig;

/**
 * OmniP is an interface for working with OmniP system
 */
@interface CorelibOmniP : NSObject <goSeqRefInterface, CorelibOmniP> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * Login to verify current user
return True if login success
 */
- (BOOL)login:(NSString*)userID accessToken:(NSString*)accessToken;
/**
 * Logout current user, subsequence calls will be failed as unauthorized
 */
- (void)logout;
/**
 * Submit data to OmniP, only for authorized users
return True if success
 */
- (BOOL)submit:(NSData*)data;
@end

@interface CorelibZpConfig : NSObject <goSeqRefInterface, CorelibZpConfig> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (NSData*)getValueForKey:(NSString*)jsonkeys error:(NSError**)error;
@end

#endif
